[tool.poetry]
name = "taskflow"
version = "0.1.0"
description = ""
authors = ["Arthur <artyr-xamidullin@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.5"
uvicorn = "^0.32.1"
redis = "^5.2.0"
python-jose = "^3.3.0"
passlib = "^1.7.4"
sqlalchemy = "^2.0.36"
asyncpg = "^0.30.0"
aiosqlite = "^0.20.0"
httpx = "^0.28.1"
alembic = "^1.14.1"
bcrypt = "^4.2.1"
pyjwt = "^2.10.1"
pydantic-settings = "^2.7.1"
python-multipart = "^0.0.20"
cryptography = "^44.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
